### ISSUE TITLE
Rule for "software"

### ISSUE THREAD

**Issue by Toflar** [doctrine/inflector#107]
I just noticed that ApiPlatform generates `/softwares` from an entity called `Software`. I might be wrong but imho this is an irregular one and uncountable, so plural of `software` should remain `software`. Or am I wrong here? (not native English) Haven't had the time to look into the lib in detail so just leaving this here before I forget about it instead of submitting a PR 😄

**Comment by jwage** [comment]
Yes, it needs to be added to the list of irregular words.

**Comment by icanhazstring** [comment]
The provided PR should solve this one.

**Comment by icanhazstring** [comment]
@jwage think this can be closed as well then :)
