### ISSUE TITLE
Meta is always 'singularized' to Metum.

### ISSUE THREAD

**Issue by MadMikeyB** [doctrine/inflector#112]
Preface: I explain this a little more in https://github.com/laravel/framework/issues/26657

When using the [Inflector::singular](https://github.com/doctrine/inflector/blob/master/lib/Doctrine/Inflector/Inflector.php#L88) method on the string 'Meta', it is singularized into 'Metum'.

According to [Wiktionary](https://en.wiktionary.org/wiki/metas#English), this behaviour is incorrect and Meta is actually the singular of Metas.

Could I request that a new Rule is added to catch this behaviour?

I am unsure if the word 'Meta' should be added to the [English Uninflected Rule Set](https://github.com/doctrine/inflector/blob/master/lib/Doctrine/Inflector/Rules/English/Uninflected.php) or handled inside the [English Inflectible Rule Set](https://github.com/doctrine/inflector/blob/master/lib/Doctrine/Inflector/Rules/English/Inflectible.php) - however if guidance is given I am happy to raise a PR to address.

**Comment by malarzm** [comment]
If "meta" is already singular then why passing it to `singularize` method?

**Comment by alcaeus** [comment]
A quick test reveals that pluralisation of "Meta" and singularisation of "Metas" works as expected:
```
php > var_dump(Doctrine\Common\Inflector\Inflector::singularize('Metas'));
php shell code:1:
string(4) "Meta"
php > var_dump(Doctrine\Common\Inflector\Inflector::pluralize('Meta'));
php shell code:1:
string(5) "Metas"
```

Be aware that passing a word that is already singular to the `singularize` method (and vice-versa) is not supported and can yield weird results. That's not a use-case cover. Closing as `invalid`.

**Comment by jwage** [comment]
I believe I fixed this in master (2.0) but does not behave the same in older versions.

**Comment by MadMikeyB** [comment]
```
>>> var_dump(Doctrine\Common\Inflector\Inflector::singularize('Metas'));
string(4) "Meta"
=> null
>>> var_dump(Doctrine\Common\Inflector\Inflector::singularize('Meta'));
string(5) "Metum"
=> null
>>> var_dump(Doctrine\Common\Inflector\Inflector::pluralize('Meta'));
string(5) "Metas"
=> null
```

Second result is the issue at the moment.

I shall investigate what version is being pulled into laravel/framework and report back.

**Comment by MadMikeyB** [comment]
`laravel/framework` is using 1.1

```
        "doctrine/inflector": "^1.1",
```

Is 2.0 tagged, do you know @jwage ?

**Comment by jwage** [comment]
Not yet. 2.0 is still in progress. I expect to release something at the beginning of the new year.
