### ISSUE TITLE
Singularizing "intensives" becomes "intensife"

### ISSUE THREAD

**Issue by dmaksimov** [doctrine/inflector#118]
Doing 
```php
Doctrine\Common\Inflector\Inflector::singularize('intensives')
``` 
returns
```
"intensife"
```

**Comment by alcaeus** [comment]
Judging by the method signature, I'm assuming you're using version 1.x of the inflector. If you can, please send a PR to the 1.3.x branch of the repository with a fix. You can see the irregular words [here](https://github.com/doctrine/inflector/blob/45d9b132b262c1d03835cdeefd42938d881556fa/lib/Doctrine/Common/Inflector/Inflector.php#L82) and [here](https://github.com/doctrine/inflector/blob/45d9b132b262c1d03835cdeefd42938d881556fa/lib/Doctrine/Common/Inflector/Inflector.php#L209) as well as some [unit tests](https://github.com/doctrine/inflector/blob/45d9b132b262c1d03835cdeefd42938d881556fa/tests/Doctrine/Tests/Common/Inflector/InflectorTest.php#L15).

**Comment by nschoellhorn** [comment]
Looking at [the dictionary](https://www.merriam-webster.com/dictionary/intensive), the noun "intensive" does not have a plural form "intensives". I don't know what the intended behaviour is when passing a word that doesn't exist/is wrong, but I think this is not necessarily a bug.

**Comment by jwage** [comment]
As mentioned above, I don't believe this is a bug. If someone believes we should handle this case, please reopen with justification.
