### ISSUE TITLE
brewery singularized becomes breweryie

### ISSUE THREAD

**Issue by ChrisThompsonTLDR** [doctrine/inflector#126]
https://github.com/doctrine/inflector/blob/8c913b9bab8d797c223e11939604149617dcc3ca/lib/Doctrine/Inflector/Inflector.php#L492

`brewery` singularized comes out as `breweryie` when it should stay `brewery`

**Comment by alcaeus** [comment]
`brewery` is already singular, as the plural is `breweries`. IIRC, passing singular words to `singularize` is not supported. @jwage probably knows better than me though.

**Comment by ChrisThompsonTLDR** [comment]
We pass thousands of singular words through the singular inflector and never see them get mangled. 

We do the same with pluralize.

**Comment by garrettw** [comment]
[Nevertheless](https://github.com/doctrine/inflector/issues/112#issuecomment-443100906):
> Be aware that passing a word that is already singular to the `singularize` method (and vice-versa) is not supported and can yield weird results. That's not a use-case cover.
