### ISSUE TITLE
Minor version breaks backwards compatibility

### ISSUE THREAD

**Issue by designermonkey** [doctrine/inflector#127]
From the Semver spec:

```
Given a version number MAJOR.MINOR.PATCH, increment the:

1. MAJOR version when you make incompatible API changes,
2. MINOR version when you add functionality in a backwards-compatible manner, and
3. PATCH version when you make backwards-compatible bug fixes.

Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.
```

The change from PHP requirements of `>=5.3.2` to `^7.0` is in breach of this spec.

Can I suggest a point release version which fixes this minimum requirement? Or that the software be repaired on all `1.x` tags, and have a MAJOR release update for the PHP requirement.

The reasoning is this breaks automatic deployments on legacy systems.

**Comment by malarzm** [comment]
I'm sorry, but we've explained in [the blogpost](https://www.doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html) why bumping PHP version in a minor release isn't considered a BC break - composer can handle such bump just fine.
