### ISSUE TITLE
Incorrect singular and plural for words such as 'canvas' and 'gas'.

### ISSUE THREAD

**Issue by eric-addcream** [doctrine/inflector#128]
With current v1.3.0 implementation:
Plural of "canvas" returns "canvas".
Singular of "canvases" returns "canvase".
Plural of "gas" returns "gas".
Singular of "gases" returns "gase".

Pluralization should be "canvases" and "gases" in US english.

**Comment by alcaeus** [comment]
That doesn't sound right. Can you please create a pull request to the 1.3.x branch with a fix? You can take a look at #69 for prior art.

**Comment by alcaeus** [comment]
Fixed in #129.
