### ISSUE TITLE
v2 release scheduled?

### ISSUE THREAD

**Issue by GrahamCampbell** [doctrine/inflector#138]
It looks like everything on the v2 milestone is done, and v2 contains some important bug fixes that 1.3.x does not. Will there be a 2.0.0 release soon? Refs https://github.com/laravel/framework/pull/31601.

**Comment by alcaeus** [comment]
We have https://github.com/doctrine/inflector/issues/100 left to do to complete support for everything that's in 1.x, after which we can release 2.0 (which will be backward compatible with 1.x).

You mentioned important bug fixes that are in 2.0 but not in 1.x, could you please mention what you're looking for? Those should definitely be back ported to 1.x.

**Comment by GrahamCampbell** [comment]
They are described in the linked issue.

**Comment by alcaeus** [comment]
Sorry, I didn't see that. I'll see if I can backport those fixes soon. Thanks for bringing it to my attention!

**Comment by alcaeus** [comment]
2.0 has been released yesterday, along with 1.4 providing the same API without BC breaks.
