### ISSUE TITLE
roave-backward-compatibility-check.phar confuse my phpstorm

### ISSUE THREAD

**Issue by ruoge3s** [doctrine/inflector#144]
"roave-backward-compatibility-check.phar" 

make the phpstome dont know use which one

```
Multiple definitions exist for class 'LogLevel'
class LogLevel \Psr\Log\LogLevel
```

<img width="1199" alt="22" src="https://user-images.githubusercontent.com/18730233/81471109-70aa3380-9221-11ea-86b4-7632c4d9befe.png">

**Comment by greg0ire** [comment]
I think we would welcome a pull request changing [this file](https://github.com/doctrine/inflector/blob/master/.gitattributes) to ignore the phar

**Comment by greg0ire** [comment]
Or maybe it shouldn't be under version control at all? @alcaeus , you introduced it in https://github.com/doctrine/inflector/commit/ab5de36233a1995f9c776c741b803eb8207aebef, was that deliberate?

**Comment by alcaeus** [comment]
No, that was an accident. Sorry.

**Comment by alcaeus** [comment]
Note, you can work around this problem by ignoring the file in phpstorm until this is fixed.

**Comment by ruoge3s** [comment]
> Note, you can work around this problem by ignoring the file in phpstorm until this is fixed.

yeah，its work!
