### ISSUE TITLE
Taxon resolution ruleset change

### ISSUE THREAD

**Issue by lchrusciel** [doctrine/inflector#147]
Hey folks 👋 

First of all, thanks for all the work you've put into all doctrine repositories.

Recently, you've published version 1.4, which fixed how taxon is pluralized, however, this fix fails a lot of Sylius builds. Even tho, proper plural form of a taxon is taxa, for the last few years, we were using taxons (and TBH no one spotted a problem with it. I guess it is due to not the common usage of this word and not too much of native speakers in our community). We are using an inflector to dynamically create routes, which blocked part of our admin panel after the update (`admin/taxons` became `admin/taxa`).

Nonetheless, we had to conflict with the newest inflector to make our builds pass. Not sure, if there is anything to fix on your side, as you in the core of the problem improved this library, but your fix broke backward compatibility at least for our project. I'm posting it here, so maybe some of you would have some recommendations for us, how to fix it on our side. Also, maybe this issue will be useful for some other folks out there.

As a ref. https://github.com/Sylius/Sylius/pull/11441

**Comment by greg0ire** [comment]
I would recommend you redirect `admin/taxons` to `admin/taxa`, and trigger a deprecation when `admin/taxons` is in use.

**Comment by alcaeus** [comment]
As this fixed a bug, we won't change it back. However, if you want to preserve the original behaviour, you can add the following call (works in the legacy API as well) to ensure you always have the correct translation:
```php
Inflector::rules('plural', ['taxon' => 'taxons']);
```

This will make sure that "taxon" will be pluralised to "taxons" and vice-versa.

**Comment by ambroisemaupate** [comment]
```
Inflector::rules('plural', ['taxon' => 'taxons']);
```

triggers a warning as `taxon` is used as a regex pattern. This should be 

```
Inflector::rules('plural', ['/taxon/i' => 'taxons']);
```
