### ISSUE TITLE
"work" pluralizing as "work"

### ISSUE THREAD

**Issue by aiwozhe** [doctrine/inflector#153]
After updating from 1.3.1 to 1.4.1, my Laravel project is failing because it is pluralizing "work" to "work"

**Comment by sander3** [comment]
Another one:

`Experience` -> `Experience`

**Comment by jochensengier** [comment]
> 
> 
> Another one:
> 
> `Experience` -> `Experience`

I’m experiencing the same issue (no pun intended):

```
>>> Str::singular('experiences')
=> "experience"
>>> Str::plural('experience')
=> "experience"
```

**Comment by slackernrrd** [comment]
I had the same issue with "experience" in Laravel, which caused Eloquent to suddenly not find a database table.

**Comment by alcaeus** [comment]
Please create pull requests to the 1.4 branch. Thanks!
