### ISSUE TITLE
Pluralization of 'weather'

### ISSUE THREAD

**Issue by tomcastleman** [doctrine/inflector#158]
The word weather has 2 valid plurals `weather|weathers` depending on context.

<1.4.0 returns `weathers` whereas >=1.4.0 returns `weather`.

This BC break broke something in an app, however I have worked around it for now.

More generally a decision would need to be made on which to use in this package.

**Comment by alcaeus** [comment]
As with other words (e.g. "homework", "research"), I believe "weather" is one of those words that are considered uncountable most of the time and thus pluralised to "weather" instead of "weathers".

If you're relying on the plural being "weathers", I would suggest creating a custom rule for this.
