### ISSUE TITLE
Pluralization of word `research`

### ISSUE THREAD

**Issue by Borkache** [doctrine/inflector#166]
During the update from 1.3.1 to 1.4.3 pluralization of word `research` to `researches` was ruined. Now it's `research` for both conditions

**Comment by greg0ire** [comment]
Duplicate of #156

**Comment by greg0ire** [comment]
Please have a look at related issues.

**Comment by GrahamCampbell** [comment]
`research` is the correct pluralisation, 1.3.1 was pluralising it incorrectly.
