### ISSUE TITLE
'progress' pluralize as 'progress'

### ISSUE THREAD

**Issue by alexmihel** [doctrine/inflector#170]
"version": "2.0.3"

**Comment by GrahamCampbell** [comment]
Right, and what's the bug?

**Comment by alexmihel** [comment]
> Right, and what's the bug?

English is not my native language. I use inflector package with Laravel. And after updating this package my Eloquent model called "Progress" can't find a table 'progresses' which automatically pluralized from 'progress'. I fixed it in Laravel and thought that it is a bug in package but after reading rules about plural form of "progress" I understood - it's not a bug. Sorry)
