### ISSUE TITLE
Documentation Depreciation Statement not Correct

### ISSUE THREAD

**Issue by dotsam** [doctrine/inflector#171]
The documentation for both 1.4.3 and for 2.0.3/2.1 both state:

> The API present in Inflector 1.x is still available, but will be deprecated in a future release and dropped for 3.0. Support for languages other than English is available in the 2.0 API only.

However this statement seems to have been written for the 1.x branch, and at a time at which removal was planned for a "3.0" release rather than 2.0.

Could the documentation for both releases be updated to clarify the reality of the situation, that the old API is deprecated as of 1.4.x, and is dropped in 2.0?

**Comment by beberlei** [comment]
Fixed in #172
