### ISSUE TITLE
Weird string replacement on Laravel

### ISSUE THREAD

**Issue by netunof** [doctrine/inflector#188]
Hello there devs, today i found out an annoying problem with routing:

Route::resource('dentista', DentistaController::class);

please note the 'ta' at the end of the word

doing a php artisan route:list i get:

GET|HEAD | dentista | dentista.index | App\Http\Controllers\DentistaController@index | web
POST | dentista | dentista.store | App\Http\Controllers\DentistaController@store | web
GET|HEAD | dentista/create | dentista.create | App\Http\Controllers\DentistaController@create | web
GET|HEAD | dentista/{dentistum} | dentista.show | App\Http\Controllers\DentistaController@show | web
PUT|PATCH | dentista/{dentistum} | dentista.update | App\Http\Controllers\DentistaController@update | web
DELETE | dentista/{dentistum} | dentista.destroy | App\Http\Controllers\DentistaController@destroy | web
GET|HEAD | dentista/{dentistum}/edit | dentista.edit | App\Http\Controllers\DentistaController@edit | web

notice the replacing of 'ta' with 'um'. That happens with any word that ends in 'ta'

**Comment by stof** [comment]
This repository is not part of Laravel
