### ISSUE TITLE
Issue with 'cookies'

### ISSUE THREAD

**Issue by DannyCooper** [doctrine/inflector#235]
Is there any way to fix this issue where the singular of cookies is cooky, or is it intended behaviour?

```php
use Doctrine\Inflector\InflectorFactory;

$inflector = InflectorFactory::create()->build();

echo $inflector->singularize('cookies'); 
// returns 'cookie'

echo $inflector->singularize('chocolate cookies'); 
// returns 'chocolate cooky'
```

**Comment by malarzm** [comment]
Unfortunately we do not support multiple words in singularize (or any other method). Best course of action is taking chocolate off cookies and adding it back later to singularized one :)

**Comment by DannyCooper** [comment]
Thanks for the clarification, @malarzm. :D
