### ISSUE TITLE
Wrong pluralization of "axis"

### ISSUE THREAD

**Issue by Vlad6847** [doctrine/inflector#240]
It returns "axiss" instead of "axes".

[What Is the Plural of Axis?](https://www.splashlearn.com/math-vocabulary/geometry/axis-plural-axes#1-what-is-the-plural-of-axis)

**Comment by iurciuc** [comment]
Pull request: https://github.com/doctrine/inflector/pull/241

**Comment by malarzm** [comment]
Closing in favour of PR
