### ISSUE TITLE
Version 1.2 switches PHP requirement from 5.6 to 7.0

### ISSUE THREAD

**Issue by dmnc** [doctrine/inflector#52]
Should this be considered an API incompatible change that triggers a major version bump to 2.0.0?

**Comment by alcaeus** [comment]
No. Composer will not install 1.2 if you're running PHP < 7.0, so there's no BC break involved. Closing as `invalid`.

**Comment by dmnc** [comment]
I have a package that is installed and run in multiple environments. It has a a minimum PHP version but not a maximum one.

It depends on illuminate/support rather than doctrine/inflector directly.

Because there isn't a major version bump here, `composer update` must always be run on the lowest supported version in order for it to build successfully on all other versions.

There is of course a way round it by introducing doctrine/inflector as a direct dependency and putting a maximum in the version constraint but this feels to me like something that Semantic Versioning is very good at solving.

**Comment by alcaeus** [comment]
No. The solution is either providing a lock file for the appropriate PHP version or none at all.
To generate an appropriate lock file, call composer update on the correct platform or use platform.config as indicated in the blog post.

**Comment by dmnc** [comment]
Your mind clearly isn't going to be changed. I've read the blog post, and like many commenters I disagree that this is an approach that is best for the community.

This also seems all the more disappointing given that #47 seems to imply that dropping support was for ideological rather than functional reasons.

**Comment by alcaeus** [comment]
> I've read the blog post, and like many commenters I disagree that this is an approach that is best for the community.

Quite frankly, this is not a problem if your environment is set up correctly. If you need to provide a lock file that works on different PHP versions, don't. That is not going to work. If you're not providing a lock file, there are ways to properly composer this to avoid running into problems.

Let me bring an example: I provide a package in version 1.0. Version 1.1 adds functionality that requires a PHP extension. The solution is simple: add whatever class depends on the extension, add a requirement for the extension to composer.json and tag 1.1.
Now, whoever uses the library with a `^1.0` version constraint will only get the new 1.1 version *if they have the extension installed*. If the extension is not installed, it won't be upgraded. However, upgrading on a system with the extension and running the code on a system without is going to cause issues.

It's the same with the PHP version: unless you run `composer update` on a system with the same PHP and extension versions as your deployment system, you're going to have a bad time. Only workaround: `platform.config`.

**Comment by GrahamCampbell** [comment]
If you need to target a specific php version, you should use the platform config, eg:

![image](https://user-images.githubusercontent.com/2829600/29091151-e208a5c2-7c79-11e7-9cea-458cb157636b.png)

You may want to put a 5.x version in there. :)

**Comment by dmnc** [comment]
I'm aware of the workarounds and I understand how composer resolves dependencies using platform as well as package requirements.

That doesn't mean this was the best approach to take in order to cause the community fewest headaches. Outside of idealised conditions, environments are different, knowledge is not perfect and this will cause people problems. A major version bump would seem a harmless solution, but I may well be missing something in the way the tree of doctrine packages fit together. The blog post doesn't seem to give any explanation for this, why support was dropped, or why 7.1 was chosen. 

I was simply registering my disappointment, especially given I can't see any actual reason in the release for removing support other than developer preference. For a package with good test coverage and multi-version CI, it just seems unnecessary to reduce support to the most recent PHP version.

I suppose I'm venting really, so apologies for that.
