### ISSUE TITLE
Composer version issue

### ISSUE THREAD

**Issue by Tamce** [doctrine/inflector#56]
I think maybe you should update your main version number when updating php requirement from `>=5.3.2` to `^7.0`.
Now there is a problem when i was installing requirements by using `composer install` because `illuminate/support` requires `doctrine/inflector ~1.0`, and the php version requirement is `>=5.3.2` in version `1.1.0` while `php: ^7.0` in version `1.2.0`.
So i can not install the requirements properly.

**Comment by Tamce** [comment]
i've seen that by using "config.platform.php" to specify the php version to solve this problem.
but i still think maybe it is better to bump the version to `2.0.0` while updating php requirements to `7.0`

**Comment by alcaeus** [comment]
`config.platform.php` is the proper way to specify the environment if dev and prod differ.

Dropping support for PHP versions is not a BC break, see [this blog post](http://doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html) for more details.
