### ISSUE TITLE
Other language inflector

### ISSUE THREAD

**Issue by gpalli** [doctrine/inflector#57]
It would be nice customize the inflector at specific langauge like Spanish there are several differences with this:

Example: 
    Singular -> Plural
    Persona -> Persona(s) .  ( It works with english too!)
    Pais -> Pais(es)
   
Other langauges like Portugues, Italian, etc has different rules with singular and plural.

**Comment by jwage** [comment]
This capability has been made possible in https://github.com/doctrine/inflector/pull/97

If you are interested in adding other languages, please submit a pull request with the rules and tests. Thanks!
