### ISSUE TITLE
Class 'Doctrine\Common\Inflector\Inflector' not found while testing

### ISSUE THREAD

**Issue by ajthinking** [doctrine/inflector#61]
For testing this package I assumed the following commands would suffice:

    git clone doctrine/inflector
    composer install
    phpunit

It does test, but all tests fail with trace:

    Error: Class 'Doctrine\Common\Inflector\Inflector' not found
    
But I see it should be loaded with prf-4 from the libs folder according to composer.json.
Was there some step I missed? I am new to phpunit so this probably an error on my side.

**Comment by alcaeus** [comment]
Have you tried running the built-in phpunit version? `vendor/bin/phpunit` works for me.

**Comment by ajthinking** [comment]
Yes, that was it thanks alot! Running vendor/bin/phpunit and all is fine. So Ill close the issue.
If you dont mind me asking what is the point of globally installed phpunit. Should I ever use that one?

**Comment by alcaeus** [comment]
I don't know why you have it installed globally. I add it to the dev dependencies of a package since I want to specify which versions to use. I also write code that extends those classes (like every test does), so I want those parent classes to live in my vendor folder.

**Comment by ajthinking** [comment]
Makes alot of sense. Thanks!
