### ISSUE TITLE
Pluralizing 'employee-child' becomes 'employee-ehildren'

### ISSUE THREAD

**Issue by JeroenVanOort** [doctrine/inflector#63]
And '-child' becomes '--hildren'. How should we fix this?

Would it be helpful if I'd create a PR with a failing test?

**Comment by jwage** [comment]
Hi @JeroenVanOort, thanks for the report. We would gladly accept a pull request with this improvement along with tests.

**Comment by jwage** [comment]
This is fixed in the master branch and will be included in the 2.0 stable release.
