### ISSUE TITLE
The pluralization does not work with multi-word terms

### ISSUE THREAD

**Issue by jovic1987** [doctrine/inflector#64]
Cases:

1. **License to practice dentistry** should be **Licenses to practice dentistry**, not **License to practice dentistries**.
2. **Transcript of record** should be **Transcripts of records** .
3. **Proof of payment of registration fee** should be **Proofs of payment of registration fees**.

**Comment by alcaeus** [comment]
I believe you got something wrong. This library is used to inflect single words for use in code generation. Example: you have a property called `$children`. This library is used to inflect the method names `addChild`, `removeChild` and `getChildren` - nothing else. It is not supposed to be used to pluralize entire sentences, that's far not the scope of this library, sorry.

Closing as `invalid`.
