### ISSUE TITLE
Incompatibility with php 7.0

### ISSUE THREAD

**Issue by flavioh825** [doctrine/inflector#77]
Hello, this morning, when I was running the composer install command on my php server, I had the following error:

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/inflector v1.3.0 -> satisfiable by doctrine/inflector[v1.3.0].
    - doctrine/inflector v1.3.0 requires php ^7.1 -> your PHP version (7.0.25) does not satisfy that requirement.
  Problem 2
    - Installation request for symfony/css-selector v4.0.4 -> satisfiable by symfony/css-selector[v4.0.4].
    - symfony/css-selector v4.0.4 requires php ^7.1.3 -> your PHP version (7.0.25) does not satisfy that requirement.
  Problem 3
    - Installation request for symfony/event-dispatcher v4.0.4 -> satisfiable by symfony/event-dispatcher[v4.0.4].
    - symfony/event-dispatcher v4.0.4 requires php ^7.1.3 -> your PHP version (7.0.25) does not satisfy that requirement.
  Problem 4
    - Installation request for doctrine/instantiator 1.1.0 -> satisfiable by doctrine/instantiator[1.1.0].
    - doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (7.0.25) does not satisfy that requirement.
  Problem 5
    - doctrine/inflector v1.3.0 requires php ^7.1 -> your PHP version (7.0.25) does not satisfy that requirement.
    - laravel/framework v5.5.35 requires doctrine/inflector ~1.1 -> satisfiable by doctrine/inflector[v1.3.0].
    - Installation request for laravel/framework v5.5.35 -> satisfiable by laravel/framework[v5.5.35].
`
At some point these packages worked on my php 7.0.25 and now they no longer run, just with php 7.1, how can I fix this, knowing that I only have php 7.0.25 support on my server?

**Comment by alcaeus** [comment]
You most likely ran `composer update` on PHP 7.1 and deployed to 7.0. Please read our blog post on this and fix your development environment appropriately: http://www.doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html. This has also already been explained in #52.

**Comment by flavioh825** [comment]
Thank you! It works perfectly!
